services:
  db:
    image: postgres:15
    container_name: ponto-db
    environment:
      POSTGRES_DB: db_ponto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db_ponto-api.sql:/docker-entrypoint-initdb.d/db_ponto-api.sql
    networks:
      - ponto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_ponto"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ponto-api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/db_ponto
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_SCHEMA=ponto
    networks:
      - ponto-network
    depends_on:
      db:
        condition: service_healthy

networks:
  ponto-network:
    driver: bridge